# Generated by Django 2.2.1 on 2019-07-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_page', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='created/')),
            ],
        ),
    ]
