# Generated by Django 2.2.1 on 2019-07-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_page',
            name='document',
            field=models.CharField(max_length=2500),
        ),
    ]
